// Korean → English translations for car catalog

const BRANDS: Record<string, string> = {
  // Korean domestic
  "현대": "Hyundai",
  "기아": "Kia",
  "제네시스": "Genesis",
  "쌍용": "SsangYong",
  "KG모빌리티": "KG Mobility",
  "KG모빌리티(쌍용)": "KG Mobility",
  "쉐보레": "Chevrolet",
  "쉐보레(GM대우)": "Chevrolet",
  "한국GM": "Chevrolet",
  "GM대우": "Chevrolet",
  "대우": "Daewoo",
  "르노코리아": "Renault Korea",
  "르노삼성": "Renault Korea",
  "르노코리아(삼성)": "Renault Korea",
  "삼성": "Samsung",
  "기타 제조사": "Other",
  // European imports
  "벤츠": "Mercedes-Benz",
  "아우디": "Audi",
  "폭스바겐": "Volkswagen",
  "볼보": "Volvo",
  "푸조": "Peugeot",
  "시트로엥": "Citroën",
  "피아트": "Fiat",
  "알파로메오": "Alfa Romeo",
  "벤틀리": "Bentley",
  "롤스로이스": "Rolls-Royce",
  "페라리": "Ferrari",
  "람보르기니": "Lamborghini",
  "마세라티": "Maserati",
  "애스턴마틴": "Aston Martin",
  "재규어": "Jaguar",
  "랜드로버": "Land Rover",
  "미니": "Mini",
  "포르쉐": "Porsche",
  "스마트": "Smart",
  "오펠": "Opel",
  "사브": "Saab",
  "스코다": "Škoda",
  "세아트": "SEAT",
  // American imports
  "포드": "Ford",
  "링컨": "Lincoln",
  "캐딜락": "Cadillac",
  "지프": "Jeep",
  "크라이슬러": "Chrysler",
  "닷지": "Dodge",
  "뷰익": "Buick",
  "GMC": "GMC",
  "테슬라": "Tesla",
  // Japanese imports
  "도요타": "Toyota",
  "렉서스": "Lexus",
  "혼다": "Honda",
  "닛산": "Nissan",
  "인피니티": "Infiniti",
  "마쓰다": "Mazda",
  "미쓰비시": "Mitsubishi",
  "스바루": "Subaru",
  "스즈키": "Suzuki",
  "이스즈": "Isuzu",
  "다이하쓰": "Daihatsu",
  "아큐라": "Acura",
  // Chinese imports
  "비야디": "BYD",
  "지리": "Geely",
  "창안": "Changan",
  "상하이자동차": "SAIC",
};

// IMPORTANT: longer phrases must come BEFORE shorter sub-strings
const MODEL_WORDS: [string, string][] = [
  // ── Hyundai ──
  ["더 뉴 그랜드 스타렉스", "The New Grand Starex"],
  ["그랜드 스타렉스", "Grand Starex"],
  ["아이오닉5", "Ioniq 5"],
  ["아이오닉6", "Ioniq 6"],
  ["아이오닉", "Ioniq"],
  ["LF 쏘나타", "LF Sonata"],
  ["쏘나타 뉴 라이즈", "Sonata New Rise"],
  ["쏘나타 하이브리드", "Sonata Hybrid"],
  ["쏘나타", "Sonata"],
  ["더 뉴 아반떼", "The New Avante"],
  ["올 뉴 아반떼", "All New Avante"],
  ["아반떼", "Avante"],
  ["팰리세이드", "Palisade"],
  ["올 뉴 투싼", "All New Tucson"],
  ["투싼", "Tucson"],
  ["더 뉴 맥스크루즈", "The New MaxCruze"],
  ["맥스크루즈", "MaxCruze"],
  ["그랜저", "Grandeur"],
  ["싼타페", "Santa Fe"],
  ["넥쏘", "Nexo"],
  ["코나", "Kona"],
  ["벨로스터", "Veloster"],
  ["엑센트", "Accent"],
  ["스타리아", "Staria"],
  ["포터", "Porter"],
  ["아이30", "i30"],
  ["베뉴", "Venue"],
  // ── Kia ──
  ["더 뉴 모하비", "The New Mohave"],
  ["모하비 더 마스터", "Mohave The Master"],
  ["모하비", "Mohave"],
  ["더 뉴 쏘렌토", "The New Sorento"],
  ["쏘렌토 4세대", "Sorento 4th Gen"],
  ["쏘렌토 3세대", "Sorento 3rd Gen"],
  ["쏘렌토", "Sorento"],
  ["스포티지", "Sportage"],
  ["카니발 4세대", "Carnival 4th Gen"],
  ["카니발 3세대", "Carnival 3rd Gen"],
  ["카니발", "Carnival"],
  ["K5 3세대", "K5 3rd Gen"],
  ["K5 2세대", "K5 2nd Gen"],
  ["더 뉴 K7", "The New K7"],
  ["더 뉴 K3", "The New K3"],
  ["셀토스", "Seltos"],
  ["니로", "Niro"],
  ["스팅어", "Stinger"],
  ["트레일블레이저", "TrailBlazer"],
  ["더 뉴 레이", "The New Ray"],
  ["레이", "Ray"],
  ["모닝", "Morning"],
  ["봉고", "Bongo"],
  ["스토닉", "Stonic"],
  // ── Chevrolet ──
  ["더 넥스트 스파크", "The Next Spark"],
  ["스파크", "Spark"],
  ["아베오", "Aveo"],
  ["올 뉴 크루즈", "All New Cruze"],
  ["크루즈", "Cruze"],
  ["말리부", "Malibu"],
  ["올란도", "Orlando"],
  ["트랙스", "Trax"],
  ["이쿼녹스", "Equinox"],
  ["캡티바", "Captiva"],
  ["리얼 뉴 콜로라도", "Real New Colorado"],
  ["콜로라도", "Colorado"],
  // ── SsangYong / KG Mobility ──
  ["더 뉴 렉스턴 스포츠 칸", "The New Rexton Sports Khan"],
  ["렉스턴 스포츠 칸", "Rexton Sports Khan"],
  ["렉스턴 스포츠", "Rexton Sports"],
  ["렉스턴스포츠", "Rexton Sports"],
  ["렉스턴", "Rexton"],
  ["티볼리", "Tivoli"],
  ["코란도", "Korando"],
  ["토레스", "Torres"],
  ["무쏘", "Musso"],
  // ── Renault Korea ──
  ["SM3 네오", "SM3 Neo"],
  // ── Genesis ──
  ["G80", "G80"], ["G70", "G70"], ["G90", "G90"],
  ["GV80", "GV80"], ["GV70", "GV70"], ["GV60", "GV60"],
  // ── Prefix words (after model names) ──
  ["더 뉴", "The New"],
  ["올 뉴", "All New"],
  ["리얼 뉴", "Real New"],
  // ── Body / passenger types ──
  ["캠핑카", "Camping Car"],
  ["카고", "Cargo"],
  ["밴", "Van"],
  ["9인승", "9-мест."],
  ["7인승", "7-мест."],
  ["5인승", "5-мест."],
  ["3인승", "3-мест."],
  // ── Generations ──
  ["6세대", "6th Gen"], ["5세대", "5th Gen"],
  ["4세대", "4th Gen"], ["3세대", "3rd Gen"],
  ["2세대", "2nd Gen"], ["1세대", "1st Gen"],
  // ── Fuel / drivetrain ──
  ["가솔린", "Gasoline"],
  ["디젤", "Diesel"],
  ["하이브리드", "Hybrid"],
  ["전기", "Electric"],
  ["터보", "Turbo"],
  // ── Trim words ──
  ["스탠다드레인지", "Standard Range"],
  ["롱레인지", "Long Range"],
  ["익스텐디드레인지", "Extended Range"],
  ["익스클루시브플러스", "Exclusive Plus"],
  ["익스클루시브", "Exclusive"],
  ["인스퍼레이션", "Inspiration"],
  ["프레스티지", "Prestige"],
  ["시그니처", "Signature"],
  ["프리미엄", "Premium"],
  ["모던", "Modern"],
  ["스마트", "Smart"],
  ["네오", "Neo"],
  ["스펙", "Spec"],
  ["더 마스터", "The Master"],
  ["더 볼드", "The Bold"],
  ["뷰티풀", "Beautiful"],
  ["넥스트", "Next"],
  ["크리에이티브", "Creative"],
  ["어드밴스드", "Advanced"],
  ["엔트리", "Entry"],
  ["스탠다드", "Standard"],
  ["디럭스팩", "Deluxe Pack"],
  ["래더패키지", "Leather Package"],
  ["익스트림", "Extreme"],
  ["라이즈", "Rise"],
  ["럭셔리", "Luxury"],
  ["노블레스", "Noblesse"],
  ["디럭스", "Deluxe"],
  ["트렌디", "Trendy"],
  ["플래그십", "Flagship"],
  ["그레이스", "Grace"],
  ["쿠페", "Coupe"],
  ["뉴", "New"],
  // ── Imported model words (Korean → transliteration/English) ──
  ["클래스", "Class"],
  ["그랜드 체로키", "Grand Cherokee"],
  ["체로키", "Cherokee"],
  ["컴패스", "Compass"],
  ["래니게이드", "Renegade"],
  ["랭글러", "Wrangler"],
  ["디스커버리", "Discovery"],
  ["레인지로버 이보크", "Range Rover Evoque"],
  ["레인지로버 벨라", "Range Rover Velar"],
  ["레인지로버 스포츠", "Range Rover Sport"],
  ["레인지로버", "Range Rover"],
  ["디펜더", "Defender"],
  ["카이엔", "Cayenne"],
  ["마칸", "Macan"],
  ["타이칸", "Taycan"],
  ["파나메라", "Panamera"],
  ["카이만", "Cayman"],
  ["박스터", "Boxster"],
  ["카마로", "Camaro"],
  ["익스플로러", "Explorer"],
  ["머스탱", "Mustang"],
  ["에스컬레이드", "Escalade"],
  ["에스티", "Escalade"],
  ["CT4", "CT4"], ["CT5", "CT5"], ["CT6", "CT6"],
  ["XT4", "XT4"], ["XT5", "XT5"], ["XT6", "XT6"],
  ["어드밴스드레인지", "Advanced Range"],
  ["그란투리스모", "GranTurismo"],
  ["기블리", "Ghibli"],
  ["르반떼", "Levante"],
  ["콰트로포르테", "Quattroporte"],
  ["콘티넨탈", "Continental"],
  ["플라잉스퍼", "Flying Spur"],
  ["뮬산", "Mulsanne"],
  ["로드스터", "Roadster"],
  ["스포츠백", "Sportback"],
  ["아반트", "Avant"],
  ["올로드", "Allroad"],
  ["투아렉", "Touareg"],
  ["티구안", "Tiguan"],
  ["파사트", "Passat"],
  ["골프", "Golf"],
  ["폴로", "Polo"],
  ["아테온", "Arteon"],
  ["크로스컨트리", "Cross Country"],
  ["리차지", "Recharge"],
  ["플러그인하이브리드", "Plug-in Hybrid"],
  ["세단", "Sedan"],
  ["왜건", "Wagon"],
  ["컨버터블", "Convertible"],
  ["카브리올레", "Cabriolet"],
  ["투도어", "2-Door"],
  ["포도어", "4-Door"],
];

const FUEL_TYPES: Record<string, string> = {
  "가솔린": "Бензин",
  "디젤": "Дизель",
  "LPG": "LPG/Газ",
  "전기": "Электро",
  "수소": "Водород",
  "하이브리드": "Гибрид",
  "플러그인하이브리드": "Плагин-гибрид",
  "가솔린+전기": "Гибрид",
  "가솔린+LPG": "LPG/Газ",
  "LPG(일반인 구입)": "LPG/Газ",
  "lpg": "LPG/Газ",
};

export function translateBrand(korean: string): string {
  return BRANDS[korean] ?? korean;
}

export function translateModel(korean: string): string {
  let result = korean;
  for (const [kr, en] of MODEL_WORDS) {
    result = result.replace(new RegExp(kr, "g"), en);
  }
  return result.replace(/\s+/g, " ").trim();
}

export function translateFuel(korean: string | null): string {
  if (!korean) return "—";
  return FUEL_TYPES[korean] ?? FUEL_TYPES[korean.toLowerCase()] ?? korean;
}

// Fix doubled CDN paths caused by scraper bug:
// https://ci.encar.com/carpicture10/X_/carpicture10/X_027.jpg → correct
export function fixPhotoUrl(url: string): string {
  const CDN = "https://ci.encar.com";
  if (!url.startsWith(CDN)) return url;
  const path = url.slice(CDN.length);
  const second = path.indexOf("/carpicture", 1);
  return second > 0 ? CDN + path.slice(second) : url;
}
